version: '3'
services:
# ==============================================================================
  web:
    image: verbral/php-c9:7.2-apache
    working_dir: /var/www/html
    environment:
#      APACHE_DOCUMENT_ROOT: web
      WAKATIME_API_KEY: ${WAKATIME_API_KEY}
    volumes:
      - ./:/var/www/html
      - ~/.ssh:/home/docker/.ssh
    ports:
      - 8181:8181
      - 81:80
